"""Small IV/TC helpers for GEOSldas validation workflows."""

from .climatology import (
    PentadClimatology,
    climatology_npz_is_valid,
    climatology_output_path,
    compute_pentad_climatology,
    compute_pentad_climatology_from_paths,
    daily_pair_paths,
    load_pentad_climatology_npz,
    matlab_default_min_count,
    normal_year_doy,
    pentad_index,
    save_pentad_climatology_npz,
)
from .config import ProductRoots, RunConfig
from .generation import (
    PairGenerationResult,
    PairInputPaths,
    date_range,
    generate_daily_pairs,
    load_daily_pair_npz,
    pair_npz_is_valid,
    pair_output_path,
    read_daily_pair,
    save_daily_pair_npz,
    write_daily_pair,
)
from .independent_validation import (
    IndependentValidation,
    compute_independent_validation,
    compute_independent_validation_from_paths,
    independent_validation_npz_is_valid,
    iv_output_path,
    load_independent_validation_npz,
    save_independent_validation_npz,
)
from .pairs import DailyPair, SparseObservation
from .readers import (
    read_ascat_h119_h120_model_pair,
    read_ascat_h119_h120_sparse,
    read_ascat_h121_model_pair,
    read_ascat_h121_sparse,
    read_cygnss_l3_model_pair,
    read_cygnss_l3_sparse,
    read_smap_l3_model_pair,
    read_smap_l3_sparse,
    read_smosic_model_pair,
    read_smosic_sparse,
)
from .triple_collocation import (
    TripleCollocation,
    compute_triple_collocation,
    compute_triple_collocation_from_paths,
    load_triple_collocation_npz,
    save_triple_collocation_npz,
    tc_output_path,
    triple_collocation_npz_is_valid,
)

__all__ = [
    "DailyPair",
    "IndependentValidation",
    "PentadClimatology",
    "PairGenerationResult",
    "PairInputPaths",
    "ProductRoots",
    "RunConfig",
    "SparseObservation",
    "TripleCollocation",
    "date_range",
    "daily_pair_paths",
    "climatology_npz_is_valid",
    "climatology_output_path",
    "compute_pentad_climatology",
    "compute_pentad_climatology_from_paths",
    "compute_independent_validation",
    "compute_independent_validation_from_paths",
    "compute_triple_collocation",
    "compute_triple_collocation_from_paths",
    "generate_daily_pairs",
    "independent_validation_npz_is_valid",
    "iv_output_path",
    "load_daily_pair_npz",
    "load_independent_validation_npz",
    "load_pentad_climatology_npz",
    "load_triple_collocation_npz",
    "matlab_default_min_count",
    "normal_year_doy",
    "pair_npz_is_valid",
    "pair_output_path",
    "pentad_index",
    "read_ascat_h119_h120_model_pair",
    "read_ascat_h119_h120_sparse",
    "read_ascat_h121_model_pair",
    "read_ascat_h121_sparse",
    "read_cygnss_l3_model_pair",
    "read_cygnss_l3_sparse",
    "read_smap_l3_model_pair",
    "read_smap_l3_sparse",
    "read_daily_pair",
    "read_smosic_model_pair",
    "read_smosic_sparse",
    "save_daily_pair_npz",
    "save_independent_validation_npz",
    "save_pentad_climatology_npz",
    "save_triple_collocation_npz",
    "tc_output_path",
    "triple_collocation_npz_is_valid",
    "write_daily_pair",
]
