fname = '/discover/nobackup/projects/land_da/hsaf_cdr_test/OLv7_M36_MULTI_type_13_H121/output/SMAP_EASEv2_M36_GLOBAL/rc_out/Y2016/M01/OLv7_M36_MULTI_type_13_H121.ldas_obsparam.20160101_0000z.txt';
fid = fopen(fname);
N_obs_param = fscanf(fid, '%d ', 1);
fprintf('N=%d\n', N_obs_param);
for i=1:N_obs_param
    obs_param(i).descr           = fscanf(fid, '%s ', 1);
    obs_param(i).species         = fscanf(fid, '%f ', 1);
    obs_param(i).orbit           = fscanf(fid, '%f ', 1);
    obs_param(i).pol             = fscanf(fid, '%f ', 1);
    obs_param(i).N_ang           = fscanf(fid, '%f ', 1);
    fprintf('i=%d descr=%s N_ang_class=%s N_ang_val=%s\n', i, obs_param(i).descr, class(obs_param(i).N_ang), num2str(obs_param(i).N_ang));
    obs_param(i).ang             = fscanf(fid, '%f ', obs_param(i).N_ang);
    obs_param(i).freq            = fscanf(fid, '%f ', 1);
    obs_param(i).FOV             = fscanf(fid, '%f ', 1);
    obs_param(i).FOV_units       = fscanf(fid, '%s ', 1);
    obs_param(i).assim           = fscanf(fid, '%s ', 1);
    obs_param(i).scale           = fscanf(fid, '%s ', 1);
    obs_param(i).getinnov        = fscanf(fid, '%s ', 1);
    obs_param(i).RTM_ID          = fscanf(fid, '%f ', 1);
    obs_param(i).bias_Npar       = fscanf(fid, '%f ', 1);
    obs_param(i).bias_trel       = fscanf(fid, '%f ', 1);
    obs_param(i).bias_tcut       = fscanf(fid, '%f ', 1);
    obs_param(i).nodata          = fscanf(fid, '%f ', 1);
    obs_param(i).varname         = fscanf(fid, '%s ', 1);
    obs_param(i).units           = fscanf(fid, '%s ', 1);
    obs_param(i).fcstvarname     = fscanf(fid, '%s ', 1);
    obs_param(i).fcstunits       = fscanf(fid, '%s ', 1);
    obs_param(i).path            = fscanf(fid, '%s ', 1);
    obs_param(i).name            = fscanf(fid, '%s ', 1);
    obs_param(i).maskpath        = fscanf(fid, '%s ', 1);
    obs_param(i).maskname        = fscanf(fid, '%s ', 1);
    obs_param(i).scalepath       = fscanf(fid, '%s ', 1);
    obs_param(i).scalename       = fscanf(fid, '%s ', 1);
    obs_param(i).flistpath       = fscanf(fid, '%s ', 1);
    obs_param(i).flistname       = fscanf(fid, '%s ', 1);
    obs_param(i).errstd          = fscanf(fid, '%f ', 1);
    obs_param(i).std_normal_max  = fscanf(fid, '%f ', 1);
    obs_param(i).zeromean        = fscanf(fid, '%s ', 1);
    obs_param(i).coarsen_pert    = fscanf(fid, '%s ', 1);
    obs_param(i).xcorr           = fscanf(fid, '%f ', 1);
    obs_param(i).ycorr           = fscanf(fid, '%f ', 1);
    obs_param(i).adapt           = fscanf(fid, '%f ', 1);
end
fclose(fid);
disp('DONE ALL');
